In [0]:
!apt-get install nvidia-cuda-toolkit

In [0]:
!apt-cache search pycuda

In [17]:
!apt-get install python3-pycuda

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pycuda is already the newest version (2016.1.2+git20161024-1build2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


In [9]:
!pip3 install numba

    100% |████████████████████████████████| 1.9MB 7.2MB/s 
    100% |████████████████████████████████| 15.9MB 2.3MB/s 


In [30]:
!apt install gcc

Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:7.2.0-1ubuntu1).
gcc set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


In [0]:
import os

In [0]:
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/lib/nvidia-cuda-toolkit/libdevice"

In [0]:
os.environ['NUMBAPRO_NVVM'] = "/usr/lib/x86_64-linux-gnu/libnvvm.so"

In [13]:
!nvidia-smi

Fri Aug 10 21:38:29 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P8    28W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [18]:
!apt install python3-pycuda

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pycuda is already the newest version (2016.1.2+git20161024-1build2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


In [0]:
import numpy as np

In [0]:
import time

In [0]:
import pycuda.driver as cuda

In [0]:
import pycuda.autoinit

In [0]:
from pycuda.compiler import SourceModule

In [0]:
import numpy

In [0]:
a = numpy.random.randn(4,4)

In [0]:
a = a.astype(numpy.float32)

In [0]:
a_gpu = cuda.mem_alloc(a.size * a.dtype.itemsize)

In [0]:
cuda.memcpy_htod(a_gpu, a)

In [32]:
!gcc -v

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3.2' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multi

In [49]:
!apt install gcc-4.8 g++-4.8

Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc-4.8 is already the newest version (4.8.5-4ubuntu6).
Suggested packages:
  g++-4.8-multilib gcc-4.8-doc libstdc++6-4.8-dbg libstdc++-4.8-doc
The following NEW packages will be installed:
  g++-4.8 libstdc++-4.8-dev
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.7 MB of archives.
After this operation, 38.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu artful/universe amd64 libstdc++-4.8-dev amd64 4.8.5-4ubuntu6 [1,045 kB]
Get:2 http://archive.ubuntu.com/ubuntu artful/universe amd64 g++-4.8 amd64 4.8.5-4ubuntu6 [17.6 MB]
Fetched 18.7 MB in 1s (11.1 MB/s)

78Selecting previously unselected package libstdc++-4.8-dev:amd64.
(Reading database ... 88588 files and directories currently installed.)
Preparing to unpack .../libstdc++-4.8-dev_4.8.5-4ubuntu6_amd64.deb ...
7Progress: [  0%] [...........................................

In [44]:
!which gcc-4.8

/usr/bin/gcc-4.8


In [45]:
!ls -l $(which gcc)

lrwxrwxrwx 1 root root 14 Aug 10 21:50 /usr/bin/gcc -> /usr/bin/gcc-5


In [0]:
!rm /usr/bin/gcc

In [0]:
!rm /usr/bin/g++

In [0]:
!ln -s /usr/bin/gcc-4.8 /usr/bin/gcc

In [0]:
!ln -s /usr/bin/g++-4.8 /usr/bin/g++

In [52]:
!g++ -v

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu6' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-dir

In [0]:
mod = SourceModule(""" __global__ void doublify(float *a) { int idx = threadIdx.x + threadIdx.y*4; a[idx] *= 2; } """)

In [0]:
func = mod.get_function("doublify")

In [0]:
func(a_gpu, block=(4,4,1))

In [0]:
a_doubled = numpy.empty_like(a)

In [0]:
cuda.memcpy_dtoh(a_doubled, a_gpu)

In [59]:
print("original array:")

original array:


In [61]:
print(a)

[[ 0.7830227   0.7409732   0.7846514   0.54542035]
 [ 1.4677291  -0.13527867 -0.6392986   0.01974263]
 [-0.41381785  1.2426234  -0.15250738 -0.4132871 ]
 [ 0.5800664   0.62423944 -1.1321721  -1.3258605 ]]


In [62]:
print("doubled with kernel:")

doubled with kernel:


In [63]:
print(a_doubled)

[[ 1.5660454   1.4819463   1.5693028   1.0908407 ]
 [ 2.9354582  -0.27055734 -1.2785972   0.03948527]
 [-0.8276357   2.485247   -0.30501476 -0.8265742 ]
 [ 1.1601328   1.2484789  -2.2643442  -2.651721  ]]


In [0]:
!nvidia-smi